Fixed python_package_upgrade_pip
As far as I know, there is not yet a `pip upgrade` command, only a `pip
install --upgrade`.

Previously, calling this function resulted in a fabric abort because pip
complains:

    ERROR: unknown command "upgrade"

Tested on pip==1.3.1. Also checked latests pip docs (1.4.dev1) and there
is still no `pip upgrade`.